# Site settings
title: ALMarohom
description: 
url: "https://lecmarohom.github.io" # root URL
# baseurl: "/particle" # the subpath of your site, e.g. /blog


# User settings
username: Alec Louie Marohom
user_description: An Electronics Engineering graduate who arranged a data-driven prototype for the Department of Agriculture - Sugar Regulatory Administration and Department of Science and Technology of the Philippines. Utilizes free time in casual collaborative brainstorming with colleagues in the hopes of creating a better application of technology. Currently takes interest in data-driven technological advancements and its other creative aspects and applications.
user_title: Data Scientist
email: alecmarohom15.p@gmail.com
#twitter_username: lorem_ipsum
#github_username:  lorem_ipsum
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
